apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: fluentbit
spec:
  interval: 1m
  chart:
    spec:
      chart: fluent-bit
      version: "0.19.17"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: fluentbit
  values:
    env: 
      - name: "LOG_ANALYTICS_WORKSPACE_ID"
        valueFrom:
          secretKeyRef:
            key:  workspace_id
            name: azure-log-analytics
      - name: "LOG_ANALYTICS_KEY"
        valueFrom:
          secretKeyRef:
            key:  key
            name: azure-log-analytics    
    service:
      type: ClusterIP
      port: 2020
      labels: {}
      annotations: 
        prometheus.io/path: "/api/v1/metrics/prometheus"
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true" 
    daemonSetVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File  
    daemonSetVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: etcmachineid
        mountPath: /etc/machine-id
        readOnly: true
    config:
      service: |    
        [SERVICE]
            Daemon Off
            Flush 1
            Log_Level info
            Parsers_File parsers.conf
            Parsers_File custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020
            Health_Check On

      inputs: |
        [INPUT]
            Name        tcp
            Tag         prometheus
            Listen      0.0.0.0
            Port        5170

        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            parser cri
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On
            Refresh_Interval  10    

      parser: |
        [PARSER]
            # http://rubular.com/r/tjUt3Awgg4
            Name cri
            Format regex
            Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z
            
      filters: |
        # filter out Prometheus metrics scraping the DotNet seed with 200 status
        [FILTER]
            Name    grep
            Match   *
            Exclude message /(?=.*?(HTTP GET /metrics responded 200))/

        # filter out health checks for DotNet seed with 200 status
        [FILTER]
            Name    grep
            Match   *
            Exclude message /(?=.*?(HTTP GET /healthcheck responded 200))/

        # filter out 200 status logs for Azure outputs
        [FILTER]
            Name    grep
            Match   *
            Exclude message /.*output:azure.*HTTP status=200/

        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc:443
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix     kube.var.log.containers.
            Merge_Log           On
            Merge_Log_Key       log_processed
            K8S-Logging.Parser  On
            K8S-Logging.Exclude Off

        [FILTER]
            Name          nest
            Match         kube.*
            Operation     lift
            Nested_under  kubernetes

        [FILTER]
            Name          nest
            Match         kube.*
            Operation     lift
            Nested_under  labels

        [FILTER]
            Name          nest
            Match         prometheus
            Operation     lift
            Nested_under  fields

        [FILTER]
            Name          nest
            Match         prometheus
            Operation     lift
            Nested_under  tags  

      outputs: |
        [OUTPUT]
            Name            azure
            Match           kube.*
            Log_Type        clusterlogs
            Customer_ID     ${LOG_ANALYTICS_WORKSPACE_ID}
            Shared_Key      ${LOG_ANALYTICS_KEY}
            time_generated  true

        [OUTPUT]
            Name            azure
            Match           prometheus
            Log_Type        clustermetrics
            Customer_ID     ${LOG_ANALYTICS_WORKSPACE_ID}
            Shared_Key      ${LOG_ANALYTICS_KEY}
            time_generated  true 