apiVersion: ENC[AES256_GCM,data:ARI=,iv:R8geGOSAjxUvuDsdFwzXhtmpP3GXcPtrHz5PhVF39+g=,tag:jvWGorE/F+eCIerFtWR+Dw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:PThXjtyiphe8S8cnecnAeg1hPZZICBv+QrKj1dTZNExECYV9u2e/g0GWd5zuMHQd6ZjdDkerjHWSE+HjK5Pwd1qt5kaA/jyqPkcarcXOyXie+fBnrSG+UjeZaVv9MzaunCB9ysehMoTGQ8MLCBXJJ1uwSja54ewNtcKi3vMsmfQSsewVmr9ZFidMIS8=,iv:hHnklF0GoDFmxLJ8D03zVXMjULvPUbZxnBWCXnFMJPw=,tag:DrI30nOiN8IUvrnP7GBZ7g==,type:str]
kind: ENC[AES256_GCM,data:f2RSJF7m,iv:jRnFipYIT3rKDG4Xnmd8fpz8b8k1TH2UZ+Vr1y3tMX4=,tag:xJKYsg9+ddRjg9gyat3dWQ==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:A+s+HqDYkqT++Q==,iv:OC4PL6fQXSqvzPRUliZk1Ww9bf6Mh9w/eKm7KEzJosU=,tag:wOBdPbkZq/DOZVn7cLT59A==,type:str]
    namespace: {{coral.workspace}}-{{coral.app}}-{{coral.deployment}}
type: ENC[AES256_GCM,data:k/Gd387VCirpgbbaA/4Xb8jObuK2iJFuapIZyNPg,iv:Yl0LPriIlQWUONzGsl9ox2rMkesirUwqwZ6g8s7wDT4=,tag:XoxGtzA2pUw8wgD86V1/0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-08T21:59:02Z"
    mac: ENC[AES256_GCM,data:5ljlNbebjG5oqBkHKedxSbho5uqVs++Pksifi/wF0/2kmsCNFLs/6Cr3/RZ+P301cAn/J8xTiql5N3L7Hn45Jy2NHvXav/ZaDpR5KIFiIIRhOkX21dplO1iYOkBHzzj2etUl/xNIM7O8RcQO39FptiDLLjSgO6KRvb7cwoBvzOk=,iv:wzGTmZ2H9/STJhgseEC4/L+BdFKSRBqVeV8/wovxoBQ=,tag:wzbULE+T2W+KEh4Fdw3i+g==,type:str]
    pgp:
        - created_at: "2022-04-08T21:59:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA74ZqtOD0cBFARAA2gVH9PPyKs/IRI1Hso/gKWSeovbuqBiavij8ki5iOlTs
            IVEGiA7fScAm5iSV3smN2Wys+7Ewmlr4PS7UbsSfF6jtdZy77oJW59cG+5un+r4J
            dpVHt3jIt6uDdrmxh5ByLiaIjudypnip0moLHP6uJDkZoJkFyXAGhjaHhutnY5XM
            TQfNSOUaANo17P3wBokwq9ApMIbKldF2ClYxhkfFBne+LnBtOZ/ShzHdwwthE+y6
            H3sPOwWvJ6YsscCKEKx8z/sGbKmmXb680J9PdkP+6bninLi4pnZIbSzqzuaRAFTC
            cpJTFUvpfg4iDYUG5EnAh4eXYAreqrE3moHe8qRCAQWBFKCPMZdilyn1DsrJXydX
            oKBGjn13jEEZPt0J/qHcIOEFVcOJP+pH86O/lFGKFo1E90Kw0pbxJn5O9EDNUgvR
            bv8hey1owubpwzgEbSnyAHXOU7R7xmdEiYr8eBzvodvblu3slXVDh/LqtHP+rtFR
            gQwtZBNvgkmk6MpWVCDrnSQAH1TEOiUlbxaKt9Sue03q/VOMv8OzXiLvj8o0KduJ
            5vhG/b+x50TYRsw2CmQ4pVGzZccTsbHzjxQqoqsKAcnnQfdKCN3BHI66IFxZt39j
            L1ImztIrtUgK6ESODaO6crheTNcfXbMDT+9wn3nhz7v7C/tWJk24U5wOJBah7i7S
            XgEgD8hz4s82lvcZOEa/FS87QBnrG3TTneQEPAlMACt4/HcjTJwpYbsE+HcNyI/l
            weTFUWWbuYElXBLrUsKyB4tXKeFHwCxnofGp7LvQ8G8Op2Bb2Sa0iAkT9vonrDg=
            =5x/j
            -----END PGP MESSAGE-----
          fp: 5F3CFA12F427D24555990C6659D488A7318723E3
    unencrypted_regex: ^(namespace)$
    version: 3.7.2
