kind: ApplicationAssignment
metadata:
  name: noel-ApplicationRegistration-coral-secrets-app-development-codespace
spec:
  application:
    kind: ApplicationRegistration
    name: coral-secrets-app
    workspace: noel
    target: development
  cluster: codespace
