kind: ManifestDeployment
metadata:
  name: prometheus
spec:
  workspace: coral-system
  manifests: prometheus
  targets:
    all:
      clusters: all
      patches:
        - labels-coral-system.yaml
