########
# Usage:
# * Update env.GITOPS_REPO to point to your own Cluster GitOps Repo
# * Create a GitHub Actions secret:
#   * Name: GITOPS_PAT
#   * Value: A Personal Access Token with the `repo` scope
########

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency: transform

env:
  # TODO: Replace this with your own repository
  GITOPS_REPO: <owner>/<repository>
  CORAL_LOG_FILE: coral.log
  AZURE_LOG_ANALYTICS_KEY: ${{ secrets.AZURE_LOG_ANALYTICS_KEY }}
  AZURE_LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.AZURE_LOG_ANALYTICS_WORKSPACE_ID }}

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Git
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git config --global credential.helper store
        mkdir -p ~/.config/git
        echo "https://git:${{ secrets.GITOPS_PAT }}@github.com/" > ~/.config/git/credentials

    - name: Clone Control Plane Repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        path: 'controlplane'
        token: ${{ secrets.GITOPS_PAT }}

    - name: Update template references
      working-directory: controlplane
      run: |
        sed -i -- "s|microsoft/coral-control-plane-seed|${GITHUB_REPOSITORY}|g" templates/*.yaml
        if [ -n "$(git status --porcelain)" ]; then 
          git add .
          git commit -m "[no ci] Updated template references"
          git push origin
        fi

    - name: Clone Cluster GitOps Repo
      uses: actions/checkout@v2
      with:
        repository: ${{ env.GITOPS_REPO }}
        path: 'gitops'
        token: ${{ secrets.GITOPS_PAT }}

    - name: Install Coral CLI
      run: npm i -g @coraldev/cli
    
    - name: Coral - Update Assignments
      run: coral assign ./controlplane --verbose

    - name: Commit Assignments
      id: commit_assignments
      working-directory: controlplane
      run: |
        if [ -n "$(git status --porcelain)" ]; then 
          git add .
          git commit -m "[no ci] Updated cluster assignments"
          git push origin
        else
          echo "No new assignments"
        fi

        SHA=$(git rev-parse HEAD)
        echo "::set-output name=SHA::$SHA"

    - name: Coral - Render templates
      run: coral render ./controlplane ./gitops --verbose

    - name: Coral - Update GitOps repo
      run: coral apply ./controlplane ./gitops --verbose

    - name: Commit GitOps changes
      working-directory: gitops
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Update from control plane commit ${{ steps.commit_assignments.outputs.SHA }}"
          git push origin main
        else
          echo "No changes made to cluster gitops repo"
        fi

    - name: Archive log file
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: coral-log-file
        path: ${{ env.CORAL_LOG_FILE }}